# Generated by Django 5.2.5 on 2025-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinprice',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
